swagger: '2.0'
info:
  version: 1.0.0
  title: crud
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  '/books/{id}':
    get:
      tags:
        - book
      summary: 'Find a model instance by {{id}}'
      operationId: book.findOne
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/book'
      deprecated: false
    put:
      tags:
        - book
      summary: Put attributes for a model instance and persist it
      operationId: book.replace
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/book'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/book'
      deprecated: false
    patch:
      tags:
        - book
      summary: Patch attributes for a model instance and persist it
      operationId: book.update
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/book'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/book'
      deprecated: false
    delete:
      tags:
        - book
      summary: 'Delete a model instance by {{id}}'
      operationId: book.delete
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
  /books:
    post:
      tags:
        - book
      summary: Create a new instance of the model and persist it
      operationId: book.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/book'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/book'
      deprecated: false
    get:
      tags:
        - book
      summary: Find all instances of the model
      operationId: book.findAll
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/book'
      deprecated: false
    delete:
      tags:
        - book
      summary: Delete all instances of the model
      operationId: book.deleteAll
      responses:
        '200':
          description: Request was successful
      deprecated: false
definitions:
  book:
    properties:
      id:
        type: string
      title:
        type: string
      author:
        type: string
      pages:
        type: number
    additionalProperties: false
    required:
      - title
